In [1]:
## Install numpy library
## First prefernce, if ANACONDA is installed
## conda install numpy
## Second prefence
## pip install numpy
import numpy as np

In [2]:
pwd

'D:\\DR\\DataAnalysis code'

In [3]:
myl = [1,2,30,40,-50]
print(type(myl))
# type(myl)
myl

<class 'list'>


[1, 2, 30, 40, -50]

In [4]:
# From list create array
mya = np.array(myl)
print(mya.dtype)
mya

int32


array([  1,   2,  30,  40, -50])

In [5]:
print(type(mya))
type(myl)

<class 'numpy.ndarray'>


list

In [6]:
sh = mya.shape
print(type(sh))
print(sh)
print(sh[0])

<class 'tuple'>
(5,)
5


In [7]:
mya.size

5

In [8]:
mya.itemsize

4

In [9]:
mya.dtype

dtype('int32')

In [10]:
myl

[1, 2, 30, 40, -50]

In [11]:
mylf = [1.0,2.0,3.0,4.0]
mylf

[1.0, 2.0, 3.0, 4.0]

In [12]:
myaf = np.array(mylf)

In [13]:
print(myaf.size)
myaf.itemsize

4


8

In [14]:
print(mya.size)
mya.itemsize

5


4

In [15]:
myaf.dtype


dtype('float64')

In [16]:
myaf.shape

(4,)

In [17]:
## Reshaping my 1-D
mylf = [1.0,2.0,3.0,4.0,10.0,-90,80,100,12,14,13,14]
myaf = np.array(mylf)
print(myaf.shape)
myaf

(12,)


array([  1.,   2.,   3.,   4.,  10., -90.,  80., 100.,  12.,  14.,  13.,
        14.])

In [18]:
X = myaf.reshape((2,2,3))
print(myaf.shape)
print(X.shape)
print(X)

(12,)
(2, 2, 3)
[[[  1.   2.   3.]
  [  4.  10. -90.]]

 [[ 80. 100.  12.]
  [ 14.  13.  14.]]]


In [19]:
X = myaf.reshape((6,2))
print(myaf.shape)
print(X.shape)
print(X)

(12,)
(6, 2)
[[  1.   2.]
 [  3.   4.]
 [ 10. -90.]
 [ 80. 100.]
 [ 12.  14.]
 [ 13.  14.]]


In [20]:
mylist = [9, 10, -20, 56, -4, 500, -20, 7, 8, 9]
mylist

[9, 10, -20, 56, -4, 500, -20, 7, 8, 9]

In [21]:
mya = np.array(mylist)
mya.dtype

dtype('int32')

In [22]:
## np.mean(mya)
## OR
mya.mean()

55.5

In [23]:
mya.sum()

555

In [24]:
mya.min()

-20

In [25]:
mya.argmin()

2

In [26]:
mya.argmax()

5

In [27]:
mya.std()

149.5073576784768

## Indexing and Slicing

In [28]:
print(mya.shape)
mya

(10,)


array([  9,  10, -20,  56,  -4, 500, -20,   7,   8,   9])

In [29]:
## Indexing
mya[6]

-20

In [30]:
# Slicing
print(mya[1:5])
mya[6:10]

[ 10 -20  56  -4]


array([-20,   7,   8,   9])

In [31]:
mya[5:] # index 5 to end

array([500, -20,   7,   8,   9])

In [32]:
mya[:6] # upto index 6 means excluding 6

array([  9,  10, -20,  56,  -4, 500])

In [33]:
print(mya)
mya[:] # Whole array

[  9  10 -20  56  -4 500 -20   7   8   9]


array([  9,  10, -20,  56,  -4, 500, -20,   7,   8,   9])

In [34]:
mya[-1]

9

In [35]:
myone = mya[ :5] # index start 0 to 4 (excluding 4)

In [36]:
myone

array([  9,  10, -20,  56,  -4])

In [37]:
# Assigning values
mya[5] = 10
mya[7] = 20
mya[2:5] = 1
mya

array([  9,  10,   1,   1,   1,  10, -20,  20,   8,   9])

In [38]:
mya

array([  9,  10,   1,   1,   1,  10, -20,  20,   8,   9])

In [39]:
# Getting subarray
mya_sub = mya[6:10]
print(type(mya_sub))
mya_sub


<class 'numpy.ndarray'>


array([-20,  20,   8,   9])

In [40]:
mya[10]

IndexError: index 10 is out of bounds for axis 0 with size 10

In [ ]:
mya_sub[:] = -100
mya_sub

In [ ]:
mya

In [ ]:
# copy and slicing difference
mya_copy = np.copy(mya[4:10])
mya_copy

In [ ]:
mya_copy[:] = 200
mya_copy

In [ ]:
mya

# 2-D slicing and referencing


In [ ]:
y = [x for x in range(28)]
y

In [ ]:
mya = np.array(y)
mya

In [ ]:
mym = mya.reshape((7,4))
mym

In [ ]:
# Indexing
mym[6,0:2]

In [ ]:
mym[5:7,2:4]

In [ ]:
mym[2:,2:]

In [ ]:
mym[2:5,2:]

##Boolean from Arrays / conditional statement

In [ ]:
mya

In [ ]:
type(mya)

In [ ]:
b  = mya>10
b

In [ ]:
mya[b]

In [ ]:
## Directly
mya[mya>10]

In [ ]:
myeven = mya[mya%2!=1]
myeven

## Numpy Operators

In [ ]:
new_mya = np.copy(mya)
new_mya

In [ ]:
# Element-wise addition
mya + new_mya

In [ ]:
mya - new_mya

In [ ]:
mya * new_mya

In [ ]:
mya+5

In [ ]:
mya / new_mya

In [ ]:
np.ones(10)

In [ ]:
np.zeros(5)

In [ ]:
# Creating a Identity matrix
np.eye(3,7)

In [ ]:
np.eye(4,2)

In [ ]:
print(3 ** 4)
mya ** new_mya

In [ ]:
np.eye(3)

In [ ]:
# creating numpy array
mya = np.arange(5,10)
mya

In [ ]:
# creating numpy array
# mya = np.arange(5,10)
mya = np.arange (5,-10,-2)
mya

In [ ]:
mya = np.arange(0,-11,-2)
mya

In [ ]:
mya = np.arange(100,1000,100)
mya

In [ ]:
# Generating the numbers
np.linspace (0,10,7)

In [ ]:
np.linspace(100,200, 21)

In [ ]:
a = np.array([1,2,3]) 
print(a)